[package]
name = "day-15"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cargo-nextest = "0.9.45"
itertools = "0.10.5"
regex = "1.7.0"
