[package]
name = "day-21"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cargo-nextest = "0.9.45"
num = "0.4.0"
